# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJimmy/test"
[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/test"
[social.params]
icon = "brand-instagram"

[[social]]
identifier = "reddit"
name = "Reddit"
url = "https://reddit.com/test"
[social.params]
icon = "brand-reddit"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/test"
[social.params]
icon = "brand-telegram"

